CREATE DATABASE customer_db;
USE customer_db;
Select * from customers limit 20;

--Q1 What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customers
group by gender;

Q2 What are the top 5 products with the highest average review rating?
Select product_category, Round(AVG(satisfaction_score),2) as "Average Product Rating"
from customers
group by product_category
order by avg(satisfaction_score) desc
limit 5;

Q3 Do Gold/Silver/Regular customers spend differently? Compare average spend?
SELECT 
    loyalty_status,
    COUNT(id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY loyalty_status
ORDER BY total_revenue DESC, avg_spend DESC;

Q4 What is the revenue contribution of age group?
Select age,
Sum(purchase_amount) as total_revenue
from customers
group by age
order by total_revenue desc;

Q5 Which education level customers purchase the most products?
SELECT 
    education,
    COUNT(id) AS total_customers,
    SUM(purchase_amount) AS total_products_bought,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY education
ORDER BY total_products_bought DESC;

--Q6 Which region has the highest number of products sold?
SELECT 
    region,
    COUNT(id) AS total_customers,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue_per_customer,
    ROUND(COUNT(id) * 100.0 / SUM(COUNT(id)) OVER (), 2) AS percentage_share
FROM customers
GROUP BY region
ORDER BY total_revenue DESC;